#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Append PATH
# Initialize linuxbrew
if [[ -d /home/linuxbrew ]]; then
  export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
  export PATH="/home/linuxbrew/.linuxbrew/sbin:$PATH"
fi
# Initialize rbenv
if [[ -d ${HOME}/.rbenv ]]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi
# go-lang setting
[[ -d ${HOME}/go ]] && export PATH="$HOME/go/bin:$PATH"
# Initialize nodenv
if [[ -d ${HOME}/.nodenv ]]; then
  export PATH="$HOME/.nodenv/bin:$PATH"
  eval "$(nodenv init -)"
fi
# yarn setting
if type "yarn" > /dev/null 2>&1; then
  export PATH="$PATH:`yarn global bin`"
fi
# rust setting
[[ -s "${HOME}/.cargo/env" ]] && source "$HOME/.cargo/env"
if type "rustc" > /dev/null 2>&1; then
  export RUST_SRC_PATH=$(rustc --print sysroot)/lib/rustlib/src/rust/library
fi

# Resolve duplicate paths
typeset -U path PATH

# Set alias
# ls
if type "exa" > /dev/null 2>&1; then
  alias ls='exa -F --time-style=iso'
  alias la='exa -lhaF --time-style=iso'
elif [[ -x /usr/bin/dircolors ]]; then
  test -r $HOME/.dircolors && eval "$(dircolors -b $HOME/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto -F --time-style=iso'
else
  alias ls='ls -F --time-style=iso'
fi

# Setting plugins
# fzf
[[ -s "${HOME}/.fzf.zsh" ]] && source "$HOME/.fzf.zsh"
if type fd > /dev/null 2>&1; then
  export FZF_DEFAULT_COMMAND="fd --type f --follow --hidden --exclude '**/.git/*' 2>/dev/null"
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
elif type rg > /dev/null 2>&1; then
  export FZF_DEFAULT_COMMAND="rg --files --follow --hidden --glob '!**/.git/*' 2>/dev/null"
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
fi
