#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Display Current Directory on WSL Terminal Titlebar.
if [[ $(uname -a) == Linux*Microsoft* ]]; then
  echo -ne "\e]0;  $(prompt-pwd)\007"
  chpwd(){echo -ne "\e]0; $(prompt-pwd)\007"}
fi

# Append PATH
if [[ -z $TMUX ]]; then # Suppress overloading by tmux
  #Initialize rbenv
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

# Set alias
# ls
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls -F --color=auto'
fi

# Set tmux
# Startup tmux
# This command must be executed after setting PATH
[[ -z "$TMUX" && ! -z "$PS1" ]] && tmux

# Setting plugins
# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFULT_COMMAND='ag -g ""'
